PropertyMngr/config/routes.rb
PropertyMngr::Application.routes.draw do
  resources :primes

match '/about', :controller=>'developments', :action=>'about'  
#gmaps
match 'map' => "units#map", :as=>:map

match '/voting', :controller=>'owners', :action=>'voting'

#route for contact page
match '/contact', :controller=>'developments', :action=>'contact'

#route from "developments" button
match '/devlist', :controller=>'developments', :action=>'index' 

#route for gem
match '/check', :controller=>'primes', :action=>'checkprime'
match '/validate', :controller=>'primes', :action=>'isprime'



	resources :owners do
	member do
	get "units"
	get "developments"	
	end	
	end
  	

  resources :developments do 
	member do
	get "owner"	
	end
	resources :units do
	member do
	get "owner"
	end
	end	
	end

	

root :to => "developments#index"
match '/Homepage', :controller=>'developments', :action=>'index'



  end

PropertyMngr/app/models/owner.rb
class Owner < ActiveRecord::Base

has_many :units
has_many :developments

def fullName
self.firstname + " " + self.lastname
end

end

PropertyMngr/app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  # GET /owners
  # GET /owners.xml
  def index
    @owners = Owner.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @owners }
    end
  end

  # GET /owners/1
  # GET /owners/1.xml
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @owner }
    end
  end

  # GET /owners/new
  # GET /owners/new.xml
  def new
    @owner = Owner.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @owner }
    end
  end

  # GET /owners/1/edit
  def edit
    @owner = Owner.find(params[:id])
  end

  # POST /owners
  # POST /owners.xml
  def create
    @owner = Owner.new(params[:owner])

    respond_to do |format|
      if @owner.save
        format.html { redirect_to(@owner, :notice => 'Owner was successfully created.') }
        format.xml  { render :xml => @owner, :status => :created, :location => @owner }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @owner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /owners/1
  # PUT /owners/1.xml
  def update
    @owner = Owner.find(params[:id])

    respond_to do |format|
      if @owner.update_attributes(params[:owner])
        format.html { redirect_to(@owner, :notice => 'Owner was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @owner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.xml
  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy

    respond_to do |format|
      format.html { redirect_to(owners_url) }
      format.xml  { head :ok }
    end
  end

# Voting Page: This code takes the units who don't have "Default" as their payment status of their mgmt fee, and displays them in a list
#as units that are eligible to vote, and another list of those who have "Default" and displays them in a separate list as those 
#eligible to vote.
	def voting
		@paidunits = Unit.find(:all,:conditions=>["status!='Default'"])
		@unpaidunits = Unit.find(:all,:conditions=>["status=='Default'"])
		@eligibleunits = Array.new
		@eligibleowners = Array.new
		@uneligibleowners = Array.new
		@paidunits.each do |unit|
		@eligibleunits << unit
		@eligibleowners << unit.owner
		end
		@unpaidunits.each do |unit|
		@uneligibleowners << unit.owner
		end
		#uniq! removes any duplicates
		@uneligibleowners.uniq!
		@eligibleunits.uniq!
		@eligibleowners.uniq!
	end
end

PropertyMngr/app/helpers/owners_helper.rb
module OwnersHelper
end

PropertyMngr/app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PropertyMngr/app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

PropertyMngr/app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Contact number</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @owners.each do |owner| %>
  <tr>
    <td><%= owner.firstname %></td>
    <td><%= owner.lastname %></td>
    <td><%= owner.contact_number %></td>
    <td><%= owner.email %></td>
    <td><%= link_to 'Show', owner %></td>
    <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
    <td><%= link_to 'Destroy', owner, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Owner', new_owner_path %>

PropertyMngr/app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

PropertyMngr/app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @owner.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @owner.lastname %>
</p>

<p>
  <b>Contact number:</b>
  <%= @owner.contact_number %>
</p>

<p>
  <b>Email:</b>
  <%= @owner.email %>
</p>




<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

PropertyMngr/app/views/owners/voting.html.erb
<table width="75%" >
	<tr>
		<td>
			<table border = "2">
				<tr>
					<th>Unit Address</th><th></th><th>Eligibility</th>
				</tr>
				<% @eligibleunits.each do |unit|%>,
				<tr>
					<td><%= unit.address1%></td><td></td><td>Eligible to vote</td></tr>
				<% end %>
			</table>
		</td>
		<td>
			<table border = "2">
				<tr>
					<th>Owner</th><th></th><th>Eligibility</th>
				</tr>
				<% @eligibleowners.each do |owner|%>
				<tr>
					<td><%= owner.fullName%></td><td></td><td>Eligible to vote</td></tr>
				<% end %>
			</table>
		</td>
		<td>
			<table border = "2">
				<tr>
					<th>Owner Name</th><th>Eligibility</th>
				</tr>
				<% @uneligibleowners.each do |owner|%>
				<tr>
					<td><%= owner.fullName%></td><td>Ineligible to vote</td></tr>
				<% end %>
			</table>
		</td>
	</tr>
</table>