PropertyMngr/config/routes.rb
PropertyMngr::Application.routes.draw do
  resources :primes

match '/about', :controller=>'developments', :action=>'about'  
#gmaps
match 'map' => "units#map", :as=>:map

match '/voting', :controller=>'owners', :action=>'voting'

#route for contact page
match '/contact', :controller=>'developments', :action=>'contact'

#route from "developments" button
match '/devlist', :controller=>'developments', :action=>'index' 

#route for gem
match '/check', :controller=>'primes', :action=>'checkprime'
match '/validate', :controller=>'primes', :action=>'isprime'



	resources :owners do
	member do
	get "units"
	get "developments"	
	end	
	end
  	

  resources :developments do 
	member do
	get "owner"	
	end
	resources :units do
	member do
	get "owner"
	end
	end	
	end

	

root :to => "developments#index"
match '/Homepage', :controller=>'developments', :action=>'index'



  end

PropertyMngr/app/models/prime.rb
class Prime < ActiveRecord::Base
end

PropertyMngr/app/controllers/primes_controller.rb
class PrimesController < ApplicationController
  # GET /primes
  # GET /primes.xml
  def index
    @primes = Prime.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @primes }
    end
  end

  # GET /primes/1
  # GET /primes/1.xml
  def show
    @prime = Prime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prime }
    end
  end

  # GET /primes/new
  # GET /primes/new.xml
  def new
    @prime = Prime.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prime }
    end
  end

  # GET /primes/1/edit
  def edit
    @prime = Prime.find(params[:id])
  end

  # POST /primes
  # POST /primes.xml
  def create
    @prime = Prime.new(params[:prime])

    respond_to do |format|
      if @prime.save
        format.html { redirect_to(@prime, :notice => 'Prime was successfully created.') }
        format.xml  { render :xml => @prime, :status => :created, :location => @prime }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /primes/1
  # PUT /primes/1.xml
  def update
    @prime = Prime.find(params[:id])

    respond_to do |format|
      if @prime.update_attributes(params[:prime])
        format.html { redirect_to(@prime, :notice => 'Prime was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /primes/1
  # DELETE /primes/1.xml
  def destroy
    @prime = Prime.find(params[:id])
    @prime.destroy

    respond_to do |format|
      format.html { redirect_to(primes_url) }
      format.xml  { head :ok }
    end
  end

def isprime
@input1 = params[:search_string]
@result = Checkprime.runcheck(@input1.to_i)
end

end

PropertyMngr/app/helpers/primes_helper.rb
module PrimesHelper
end

PropertyMngr/app/views/primes/_form.html.erb
<%= form_for(@prime) do |f| %>
  <% if @prime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prime.errors.count, "error") %> prohibited this prime from being saved:</h2>

      <ul>
      <% @prime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :primenum %><br />
    <%= f.text_field :primenum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PropertyMngr/app/views/primes/checkprime.html.erb
</br><h1>Enter a number to check if it is Prime</h1></br>
<%= form_tag "/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Search" %>
<% end %>

PropertyMngr/app/views/primes/edit.html.erb
<h1>Editing prime</h1>

<%= render 'form' %>

<%= link_to 'Show', @prime %> |
<%= link_to 'Back', primes_path %>

PropertyMngr/app/views/primes/index.html.erb
<h1>Listing primes</h1>

<table>
  <tr>
    <th>Primenum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @primes.each do |prime| %>
  <tr>
    <td><%= prime.primenum %></td>
    <td><%= link_to 'Show', prime %></td>
    <td><%= link_to 'Edit', edit_prime_path(prime) %></td>
    <td><%= link_to 'Destroy', prime, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prime', new_prime_path %>

PropertyMngr/app/views/primes/isprime.html.erb
Prime Number Result<br>
<%= @input1 %> is <%= @result %>

PropertyMngr/app/views/primes/new.html.erb
<h1>New prime</h1>

<%= render 'form' %>

<%= link_to 'Back', primes_path %>

PropertyMngr/app/views/primes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Primenum:</b>
  <%= @prime.primenum %>
</p>


<%= link_to 'Edit', edit_prime_path(@prime) %> |
<%= link_to 'Back', primes_path %>