PropertyMngr/config/routes.rb
PropertyMngr::Application.routes.draw do
  resources :primes

match '/about', :controller=>'developments', :action=>'about'  
#gmaps
match 'map' => "units#map", :as=>:map

match '/voting', :controller=>'owners', :action=>'voting'

#route for contact page
match '/contact', :controller=>'developments', :action=>'contact'

#route from "developments" button
match '/devlist', :controller=>'developments', :action=>'index' 

#route for gem
match '/check', :controller=>'primes', :action=>'checkprime'
match '/validate', :controller=>'primes', :action=>'isprime'



	resources :owners do
	member do
	get "units"
	get "developments"	
	end	
	end
  	

  resources :developments do 
	member do
	get "owner"	
	end
	resources :units do
	member do
	get "owner"
	end
	end	
	end

	

root :to => "developments#index"
match '/Homepage', :controller=>'developments', :action=>'index'



  end

PropertyMngr/app/models/unit.rb
class Unit < ActiveRecord::Base
belongs_to :owner
belongs_to :development

acts_as_gmappable 

   def gmaps4rails_address
      "#{self.address1}"
 end

def gmap4rails_infowindow
	"<h>#{self.address1}</h>"
	
end

end

PropertyMngr/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  # GET /units
  # GET /units.xml
  def index
   
@development= Development.find(params[:development_id]) 
@units = @development.units
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @units }
    end
  end

  # GET /units/1
  # GET /units/1.xml
  def show
    @unit = Unit.find(params[:id])
@development = Development.find(params[:development_id])
	

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @unit }
    end
  end

  # GET /units/new
  # GET /units/new.xml
  def new
    @unit = Unit.new

	#code added	
	@development= Development.find(params[:development_id])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
	@development= Development.find(params[:development_id])
  end

  # POST /units
  # POST /units.xml
  def create
    @unit = Unit.new(params[:unit])

	#code added
	@unit.development = Development.find(params[:development_id])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to(development_path(@unit.development), :notice => 'Unit was successfully created.') }
        format.xml  { render :xml => @unit, :status => :created, :location => @unit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.xml
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to(development_path(@unit.development), :notice => 'Unit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.xml
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

@development= Development.find(params[:development_id])

    respond_to do |format|
      format.html { redirect_to(development_path(@development)) }
      format.xml  { head :ok }
    end
  end

#gmaps 
def map
   @json = Unit.all.to_gmaps4rails
end
end

PropertyMngr/app/helpers/units_helper.rb
module UnitsHelper
end

PropertyMngr/app/views/units/_form.html.erb
<%= form_for([@development,@unit]) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address1 %>
  </div>
  
  <div class="field">
    <%= f.label :owner_id %><br />
    <%#= f.text_field :owner_id %>
<%=select("unit", "owner_id", Owner.all.collect {|p| [ p.fullName, p.id ] }, { :include_blank => true })%>
  </div>
<div class="field">
    <%= f.label :management_fee %><br />
    <%= f.text_field :management_fee %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
   
<!--drop down box for status-->
<select name="unit[status]">
  <option value="" ></option>
  <option value="DD" >DD</option>
  <option value="Payment Plan">Payment Plan</option>
  <option value="Paid in Full">Paid in Full</option>
  <option value="Default">Default</option>
</select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

PropertyMngr/app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Back', development_path(@development) %>

PropertyMngr/app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <tr>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.address1 %></td>
    <td><%= link_to 'Show', unit %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Destroy', unit, :confirm => 'Are you sure?', :method => :delete %></td>
    
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_unit_path %>

PropertyMngr/app/views/units/map.html.erb
<%= gmaps4rails(@json) %>

PropertyMngr/app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', development_units_path %>

PropertyMngr/app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @unit.address1 %>
</p>


<p>
<b>Owner:</b>	<%= @unit.owner.fullName %>
</p>
<p>
<b>Contact Number: </b><%= @unit.owner.contact_number %>
</p>
<p>
<b>Email: </b><%= @unit.owner.email %>
</p>
<p>
<b>Management Fee: </b><%= @unit.management_fee%>
</p>
<p>
<b>Status: </b><%= @unit.status%>
</p>

<%= link_to 'Edit', edit_development_unit_path(@development,@unit) %> |
<%= link_to 'Back', development_path(@development) %>