PropertyMngr/config/routes.rb
PropertyMngr::Application.routes.draw do
  resources :primes

match '/about', :controller=>'developments', :action=>'about'  
#gmaps
match 'map' => "units#map", :as=>:map

match '/voting', :controller=>'owners', :action=>'voting'

#route for contact page
match '/contact', :controller=>'developments', :action=>'contact'

#route from "developments" button
match '/devlist', :controller=>'developments', :action=>'index' 

#route for gem
match '/check', :controller=>'primes', :action=>'checkprime'
match '/validate', :controller=>'primes', :action=>'isprime'



	resources :owners do
	member do
	get "units"
	get "developments"	
	end	
	end
  	

  resources :developments do 
	member do
	get "owner"	
	end
	resources :units do
	member do
	get "owner"
	end
	end	
	end

	

root :to => "developments#index"
match '/Homepage', :controller=>'developments', :action=>'index'



  end

PropertyMngr/app/models/development.rb
class Development < ActiveRecord::Base
has_many :units
belongs_to :owner
end

PropertyMngr/app/controllers/developments_controller.rb
class DevelopmentsController < ApplicationController
  # GET /developments
  # GET /developments.xml
  def index
    @developments = Development.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @developments }
    end
  end

  # GET /developments/1
  # GET /developments/1.xml
  def show
    @development = Development.find(params[:id])

	@units = @development.units

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @development }
    end
  end

  # GET /developments/new
  # GET /developments/new.xml
  def new
    @development = Development.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @development }
    end
  end

  # GET /developments/1/edit
  def edit
    @development = Development.find(params[:id])
  end

  # POST /developments
  # POST /developments.xml
  def create
    @development = Development.new(params[:development])

    respond_to do |format|
      if @development.save
        format.html { redirect_to(@development, :notice => 'Development was successfully created.') }
        format.xml  { render :xml => @development, :status => :created, :location => @development }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @development.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /developments/1
  # PUT /developments/1.xml
  def update
    @development = Development.find(params[:id])

    respond_to do |format|
      if @development.update_attributes(params[:development])
        format.html { redirect_to(@development, :notice => 'Development was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @development.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/1
  # DELETE /developments/1.xml
  def destroy
    @development = Development.find(params[:id])
    @development.destroy

    respond_to do |format|
      format.html { redirect_to(developments_url) }
      format.xml  { head :ok }
    end
  end

	#added this code to show the development's units
	def showunit
		@development = Development.find(params[:id])
		@units = @development.unit
		respond_to do |format|
		format.html # show.html.erb
		format.xml { render :xml => @development }
		end
	end

	#added this to show owners
	def showowners
		@development = Development.find(params[:id])
		@owner = @development.owner

		respond_to do |format|
		format.html
		format.xml {render :xml => @development}
		end
	end

#this class is for the hardcoded details on the About Page
def about
end

#this class is for the hardcoded details on the About Page
def contact
end

end

PropertyMngr/app/helpers/developments_helper.rb
module DevelopmentsHelper
end

PropertyMngr/app/views/developments/_form.html.erb
<%= form_for(@development) do |f| %>
  <% if @development.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@development.errors.count, "error") %> prohibited this development from being saved:</h2>

      <ul>
      <% @development.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PropertyMngr/app/views/developments/about.html.erb
<html>
<!--Simple text to display on the page--> 
<body><h3>
Developed by Darragh Breathnach.</br>
Web Application Frameworks Project.</br>
Postgraduate Diploma in Cloud Computing.</br>
</h3><hr width = "35%" align = "left">

<table border = 1 cellpadding = 20>
<tr>
<td><h3>Instructions:</h3>
<p>1. Enter owner details.</p>
<p>2. Create new development or if it already exists, skip to 3.</p>
<p>3. Create unit, insert address and assign owner</p>
</td>
</tr>


</table>
</body>
</html>

PropertyMngr/app/views/developments/contact.html.erb
Darragh Breathnach</br>
Email: darragh.breathnach@student.ncirl.ie or darraghb@gmail.com</br><hr width = "35%" align = "left">

Please ensure all contacts are regarding telling me how great this application is. Criticism won't be tolerated in any form.

PropertyMngr/app/views/developments/edit.html.erb
<h1>Editing development</h1>

<%= render 'form' %>

PropertyMngr/app/views/developments/index.html.erb
<center>	<h1>Listing developments</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr></center>

<% @developments.each do |development| %>
  <tr>
    <td><%= development.name %></td>
    <td><%= link_to 'Show', development %></td>
    <td><%= link_to 'Edit', edit_development_path(development) %></td>
	
    <td><%= link_to 'Destroy', development, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= button_to 'Map', map_path %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Add New Owner', new_owner_path%>
<%= link_to 'New Development', new_development_path %>

PropertyMngr/app/views/developments/new.html.erb
<center><h1>New development</h1>

<%= render 'form' %>

<%= link_to 'Back', developments_path %></center>

PropertyMngr/app/views/developments/show.html.erb
<center><p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @development.name %>
</p>
<table>
  <tr>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.address1 %></td>
    <td><%= link_to 'Show', development_unit_path(unit.development,unit) %></td>
    <td><%= link_to 'Edit', edit_development_unit_path(unit.development,unit) %></td>
    <td><%= link_to 'Destroy', development_unit_path(unit.development,unit), :confirm => 'Are you sure?', :method => :delete %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Edit', edit_development_path(@development) %> |
<%= link_to 'Add Unit', new_development_unit_path(@development)%> |
<%= link_to 'Back', developments_path %></center>

PropertyMngr/app/views/developments/showowners.html.erb
<p id="notice"><%= notice %></p>
<p> <b>Name:</b> <%= @development.name %></p>

<hr>

<table border=1>
<tr><td>First Name:</td><td><%= @owner.firstname %></td></tr>
<tr><td>Last Name:</td><td><%= @owner.lastname %></td></tr>
<tr><td>Contact Number:</td><td><%= @owner.contact_number %></td></tr>
<tr><td>Management Fee:</td><td>£<%= @owner.management_fee %></td></tr>
<tr><td>Payment Status:</td><td><%= @owner.status %></td></tr>
</table>
<%= link_to 'Edit', edit_development_path(@development) %> 
<%= link_to 'Back', developments_path %>

PropertyMngr/app/views/developments/showunit.html.erb
<p id="notice"><%= notice %></p>

<p> <b>Name:</b> <%= @development.name %></p>

<table border=1> 
<%for unit in @units%>
<tr><td>Address :</td><td><%= unit.address1 %></td></tr>
<%end%>


</table>
<%= link_to 'Edit', edit_development_path(@development) %> 
<%= link_to 'Back', developments_path %>